### ISSUE TITLE
Failed to activate the css-clean package

### ISSUE THREAD

**Issue by v0wels** [SeanJM/css-clean#2]
[Enter steps to reproduce below:]

1. Cmd+Opt+C
2. Receive error
3. Be sad

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [css-clean](https://github.com/SeanJM/css-clean) package, v2.1.5

### Stack Trace

Failed to activate the css-clean package

```
At Cannot find module 'lasso-string'

Error: Cannot find module 'lasso-string'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/ck/.atom/packages/css-clean/main.js:1088:13)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:172:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:800:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:01.8.0 css-clean:convert (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "close-tags",
      "acf-snippets",
      "wordpress-api",
      "autosave",
      "fuzzy-finder",
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-gfm",
      "language-git",
      "language-go",
      "language-java",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-python",
      "language-shellscript",
      "language-todo",
      "language-toml",
      "language-yaml",
      "markdown-preview",
      "metrics",
      "open-on-github",
      "archive-view",
      "linter-scss-lint",
      "rainbow-selection",
      "language-textile",
      "swackets"
    ],
    "packagesWithKeymapsDisabled": [
      "php-cs-fixer"
    ],
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.13
atom-material-ui, v1.0.5
atom-minify, v0.7.1
atom-pair, v2.0.10
autoclose-html, v0.21.0
autocomplete-sass, v0.1.0
color-picker, v2.1.1
css-clean, v2.1.5
emmet, v2.4.1
file-icons, v1.6.14
imdone-atom, v1.3.25
line-diff-details, v1.2.0
linter, v1.11.3
linter-jshint, v2.0.0
linter-php, v1.1.8
minimap, v4.19.0
minimap-git-diff, v4.1.8
php-cs-fixer, v2.5.6
pigments, v0.24.1
rainbow-extensions, v1.0.4
rainbox-tabs, v2.0.0
sync-settings, v0.6.0
wordpress-dictionary, v4.4.0

# Dev
No dev packages
```

**Comment by SeanJM** [comment]
Fixed!
