### ISSUE TITLE
Uncaught TypeError: Cannot read property 'content' of undefined

### ISSUE THREAD

**Issue by marketania** [SeanJM/css-clean#20]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [css-clean](https://github.com/SeanJM/css-clean) package, v2.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'content' of undefined

```
At /Users/Marketania/.atom/packages/css-clean/main.js:111

TypeError: Cannot read property 'content' of undefined
    at Function.capture.selector (/Users/Marketania/.atom/packages/css-clean/main.js:111:16)
    at capture (/Users/Marketania/.atom/packages/css-clean/main.js:87:23)
    at cleanCss.fn.value (/Users/Marketania/.atom/packages/css-clean/main.js:519:19)
    at Object.value (/Users/Marketania/.atom/packages/css-clean/main.js:1520:24)
    at atom-text-editor.module.exports.convert (/Users/Marketania/.atom/packages/css-clean/main.js:1649:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -2:51.3.0 application:hide (atom-pane.pane.active)
     -1:36.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.7.0 css-clean:convert (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
compare-files, v0.6.2
css-clean, v2.4.0

# Dev
No dev packages
```

**Comment by SeanJM** [comment]
I'm going to close this issue until you can supply the CSS which caused the error.
