### ISSUE TITLE
Uncaught TypeError: Cannot read property '3' of null

### ISSUE THREAD

**Issue by deepak-jacob** [SeanJM/css-clean#21]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [css-clean](https://github.com/SeanJM/css-clean) package, v2.4.0

### Stack Trace

Uncaught TypeError: Cannot read property '3' of null

```
At C:\Users\djacob\.atom\packages\css-clean\main.js:421

TypeError: Cannot read property '3' of null
    at Function.capture.sass include arguments (C:\Users\djacob\.atom\packages\css-clean\main.js:421:29)
    at capture (C:\Users\djacob\.atom\packages\css-clean\main.js:87:23)
    at Object.capture.shared.nested (C:\Users\djacob\.atom\packages\css-clean\main.js:408:19)
    at Function.capture.selector (C:\Users\djacob\.atom\packages\css-clean\main.js:107:26)
    at capture (C:\Users\djacob\.atom\packages\css-clean\main.js:87:23)
    at Object.capture.shared.nested (C:\Users\djacob\.atom\packages\css-clean\main.js:408:19)
    at Function.capture.selector (C:\Users\djacob\.atom\packages\css-clean\main.js:107:26)
    at capture (C:\Users\djacob\.atom\packages\css-clean\main.js:87:23)
    at Object.capture.shared.nested (C:\Users\djacob\.atom\packages\css-clean\main.js:408:19)
    at Function.capture.selector (C:\Users\djacob\.atom\packages\css-clean\main.js:107:26)
    at capture (C:\Users\djacob\.atom\packages\css-clean\main.js:87:23)
    at Object.capture.shared.nested (C:\Users\djacob\.atom\packages\css-clean\main.js:408:19)
    at Function.capture.selector (C:\Users\djacob\.atom\packages\css-clean\main.js:107:26)
    at capture (C:\Users\djacob\.atom\packages\css-clean\main.js:87:23)
    at Object.capture.shared.nested (C:\Users\djacob\.atom\packages\css-clean\main.js:408:19)
    at Function.capture.selector (C:\Users\djacob\.atom\packages\css-clean\main.js:107:26)
    at capture (C:\Users\djacob\.atom\packages\css-clean\main.js:87:23)
    at cleanCss.fn.value (C:\Users\djacob\.atom\packages\css-clean\main.js:519:19)
    at Object.value (C:\Users\djacob\.atom\packages\css-clean\main.js:1520:24)
    at atom-text-editor.module.exports.convert (C:\Users\djacob\.atom\packages\css-clean\main.js:1649:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\djacob\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\djacob\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\djacob\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\djacob\AppData\Local\atom\app-1.8.0\resources\app.asar\src\atom-environment.js:1100:28)
    at EventEmitter.outerCallback (C:\Users\djacob\AppData\Local\atom\app-1.8.0\resources\app.asar\src\application-delegate.js:327:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -9:37.9.0 tree-view:show-in-file-manager (span.name.icon.icon-file-text)
     -0:09.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:04.5.0 css-clean:convert (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.7
css-clean, v2.4.0
minimap, v4.23.2

# Dev
No dev packages
```

**Comment by SeanJM** [comment]
Without the CSS which caused the issue, I can't solve it.

**Comment by deepak-jacob** [comment]
Here is the css snippet to test,

p {
  @include fontSize(1.4)
}

**Comment by SeanJM** [comment]
Fixed!
