### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mkrishtopa** [SeanJM/css-clean#22]
CSS file of 3500 lines of code

**Atom Version**: 1.8.0
**System**: Ubuntu 14.04.4
**Thrown From**: [css-clean](https://github.com/SeanJM/css-clean) package, v2.4.0

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /home/theo/.atom/packages/css-clean/main.js:1614

RangeError: Maximum call stack size exceeded
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:844)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
    at h (/home/theo/.atom/packages/css-clean/main.js:1614:969)
```

### Commands

```
     -0:07.7.0 core:close (atom-text-editor.editor.is-focused)
     -0:06.1.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:05.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:03.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.1.0 css-clean:convert (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "destroyEmptyPanes": false,
    "disabledPackages": [
      "pinned-tabs"
    ],
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
css-clean, v2.4.0
emmet, v2.4.3
minimap, v4.24.6
project-manager, v2.9.7

# Dev
No dev packages
```

**Comment by SeanJM** [comment]
I'm going to close this issue, but I will re-open it if you can supply the CSS which caused the error. I did push a recent update. This error may be solved.
