### ISSUE TITLE
CSS file that begins "@charset "UTF-8"; cause Uncaught TypeError

### ISSUE THREAD

**Issue by xekri** [SeanJM/css-clean#27]
`TypeError: buffer.string.length.substr is not a function
    at Object.characterSet [as character set] (/Users/blanu/.atom/packages/css-clean/src/css-clean-src/capture/modules/characterSet.js:4:40)
    at capture (/Users/blanu/.atom/packages/css-clean/src/css-clean-src/capture/capture.js:153:25)
    at CleanCss.valueOf (/Users/blanu/.atom/packages/css-clean/src/css-clean-src/cleanCss.js:29:19)
    at atom-text-editor.module.exports.convert (/Users/blanu/.atom/packages/css-clean/main.js:35:12)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)`

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.10.0
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [css-clean](https://github.com/SeanJM/css-clean) package, v2.12.2

### Stack Trace

Uncaught TypeError: buffer.string.length.substr is not a function

```
At /Users/blanu/.atom/packages/css-clean/src/css-clean-src/capture/modules/characterSet.js:4

TypeError: buffer.string.length.substr is not a function
    at Object.characterSet [as character set] (/Users/blanu/.atom/packages/css-clean/src/css-clean-src/capture/modules/characterSet.js:4:40)
    at capture (/Users/blanu/.atom/packages/css-clean/src/css-clean-src/capture/capture.js:153:25)
    at CleanCss.valueOf (/Users/blanu/.atom/packages/css-clean/src/css-clean-src/cleanCss.js:29:19)
    at atom-text-editor.module.exports.convert (/Users/blanu/.atom/packages/css-clean/main.js:35:12)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -2:10.7.0 core:paste (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  3x -2:09.8.0 core:undo (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -2:06.2.0 core:cut (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -2:03.3.0 core:undo (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -2:01.8.0 core:cut (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
 82x -1:43 core:undo (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
  4x -1:37.3.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:28.7.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:26.9.0 core:backspace (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:26.6.0 auto-id-class:insert_class_attribute (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -1:18 core:copy (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:44.4.0 editor:newline (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:44.1.0 core:paste (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:42.8.0 css-clean:convert (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:01.4.0 core:paste (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -0:00.0 css-clean:convert (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
```

### Config

```json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "wrap-guide",
      "welcome",
      "tool-bar",
      "linter",
      "atomic-chrome",
      "atom-bootstrap4",
      "atom-html-preview",
      "open-in-browser",
      "column-select",
      "react-es6-snippets",
      "react-snippets",
      "activate-power-mode"
    ],
    "packagesWithKeymapsDisabled": [
      "emmet",
      "atom-tag-wrapper"
    ],
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
accents-ui, v1.2.0 (inactive)
activate-power-mode, v0.8.1 (inactive)
adventurous-syntax, v0.2.0 (inactive)
aesthetic-ui, v2.0.0 (inactive)
atom-beautify, v0.29.11 (active)
atom-bootstrap3, v1.2.12 (inactive)
atom-bootstrap4, v1.4.0 (inactive)
atom-html-preview, v0.1.22 (inactive)
atom-material-syntax, v0.4.6 (inactive)
atom-tag-wrapper, v0.1.1 (inactive)
atom-ternjs, v0.15.0 (active)
atomic-chrome, v0.3.0 (inactive)
auto-detect-indentation, v1.2.0 (active)
auto-id-class, v0.2.6 (active)
autocomplete-html-entities, v0.1.0 (active)
autocomplete-paths, v1.0.2 (active)
cake-syntax, v0.5.3 (inactive)
color-picker, v2.2.2 (active)
column-select, v0.2.0 (inactive)
css-clean, v2.12.2 (active)
css-spy, v0.6.0 (active)
dash, v1.6.2 (inactive)
duotone-blue-dark-syntax, v1.4.0 (inactive)
duotone-light-syntax, v1.0.0 (inactive)
eclectic-syntax, v0.2.1 (inactive)
emmet, v2.4.3 (active)
ex-mode, v0.13.0 (inactive)
firewatch-syntax, v1.0.1 (inactive)
genesis-syntax, v1.0.7 (inactive)
genesis-ui, v0.5.0 (inactive)
git-plus, v5.16.2 (inactive)
git-time-machine, v1.5.3 (inactive)
github-atom-light-syntax, v0.2.0 (inactive)
gl-light-syntax, v2.2.0 (inactive)
gruvbox-plus-syntax, v1.2.5 (inactive)
gruvbox-syntax, v2.4.1 (inactive)
highlight-selected, v0.11.2 (active)
hyperclick, v0.0.37 (active)
indent-guide-improved, v1.4.9 (active)
isotope-light-ui, v2.2.6 (inactive)
language-diff, v0.4.0 (active)
lazy-light-syntax, v0.1.1 (inactive)
linter, v1.11.16 (inactive)
material-ui, v1.0.9 (inactive)
metro-ui, v2.2.2 (inactive)
minimap, v4.24.7 (active)
native-ui, v0.18.3 (inactive)
northem-light-atom-syntax, v0.20.0 (inactive)
northem-light-atom-ui, v0.4.0 (inactive)
nucleus-dark-ui, v0.9.3 (inactive)
open-in-browser, v0.4.7 (inactive)
open-recent, v5.0.0 (active)
pigments, v0.34.0 (active)
react, v0.16.0 (active)
react-es6-snippets, v0.3.0 (inactive)
react-snippets, v0.4.2 (inactive)
regex-railroad-diagram, v0.16.0 (active)
seti-syntax, v1.0.1 (inactive)
seti-ui, v1.3.2 (inactive)
sort-lines, v0.14.0 (inactive)
spacegray-atom-dark-syntax, v1.1.1 (inactive)
spacegray-dark-neue-syntax, v1.3.0 (inactive)
spacegray-dark-ui, v0.12.0 (inactive)
split-diff, v1.0.4 (inactive)
Sublime-Style-Column-Selection, v1.7.2 (active)
tango-syntax, v0.4.1 (inactive)
tool-bar, v1.0.1 (inactive)
vim-mode, v0.65.1 (active)
wombat-light-syntax, v1.1.2 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (active)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (active)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (active)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.241.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (inactive)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by SeanJM** [comment]
Fixed
